version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '80:80'
    volumes:
      - .:/code
      - ./docker/web/files/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    command: --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
